project:
  type: website

website:
  title: "SLR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: index.qmd
        text: Table of Contents
  sidebar:
    contents:
      - text: Introduction
        href: intro.qmd
      - text: Steps of SLR
        href: steps.qmd
      - text: Topics of SLR
        href: topics.qmd
      - text: Roles or Members
        href: roles.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
