project:
  type: website

website:
  title: "SLR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents:
      - text: About
  body-header: |
    This page brought to you by <https://example.com>
  margin-header: |
    ![Logo image](/img/logo.png)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
